### ISSUE TITLE
the netify deploy is down

### ISSUE THREAD

**Issue by thomhickey** [pratik227/quasar-echarts#2]
can't get to the demo

**Comment by digitalit** [comment]
No problem for me. 

Demo looks fine

**Comment by thomhickey** [comment]
Strange, it works on one of my Macs but on this one:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/9190319/107319629-09d9d500-6a54-11eb-8ad5-e78f54bbfc47.png">

**Comment by pratik227** [comment]
Strange, Demo looks fine for me.

**Comment by thomhickey** [comment]
Closing as it's probably just my computer. The one that's failing is my work computer, possibly some kind of ca cert issue.
