### ISSUE TITLE
Exporting data to CSV/PDF

### ISSUE THREAD

**Issue by L-S-ONG** [pratik227/quasar-echarts#5]
I've checked the Echarts API, it has a toolbox that includes several feature such as saveAsImage or having a Data View (https://echarts.apache.org/en/option.html#toolbox)

Are there any way that we could export the data in Excel/CSV/PDF?

**Comment by pratik227** [comment]
Hi @L-S-ONG,

Yes here is option for Image but not sure about the CSV/PDF

**Comment by pratik227** [comment]
Hi @L-S-ONG,

It's not there I think you need to use an external library.

Thanks,
Pratik Patel
